### ISSUE TITLE
Suggest edit button

### ISSUE THREAD

**Issue by wenbinyu-PU** [wenbinyugroup/ivabs#14]
@duhd1993 On the top right of page， there are three icons, the middle item, the 3rd item is Suggest edit. However, it links to a 404 page. Please fix this. For example the front page https://wenbinyugroup.github.io/ivabs/index.html links to 

https://github.com/wenbinyugroup/ivabs/edit/master/index.rst

**Comment by duhd1993** [comment]
fixed with b24af04d8c3bc0426b35f8f4350cdc6f75e29707
