### ISSUE TITLE
doc reference issue on page https://wenbinyugroup.github.io/ivabs/ivabs/install.html

### ISSUE THREAD

**Issue by wenbinyu-PU** [wenbinyugroup/ivabs#16]
@duhd1993 I don't know why the references do not work: 
:doc:`ivabs/install/python_setup`
- :doc:`ivabs/install/windows`.
- :doc:`ivabs/install/linux`. 
Similar markups worked on https://wenbinyugroup.github.io/ivabs/index.html.

**Comment by duhd1993** [comment]
fixed with 0cf2df74776807678e07dee4ea4e2ca54ec69bd7
I changed from `ivabs/install/windows` to `/ivabs/install/windows`, from relative to absolute path. /docs/source is the root folder. If you want to use relative path, should be `install/windows`.
