### ISSUE TITLE
SEO of the documentation website

### ISSUE THREAD

**Issue by wenbinyu-PU** [wenbinyugroup/ivabs#19]
@duhd1993 We need some search engine optimization for the website. It has been alive for more than one year. However, when I Google VABS or iVABS, I still cannot find it. Do you know whether there are some tricks to optimize the web site so that it can be easily indexed by Google or other search engines?

**Comment by duhd1993** [comment]
It will not be easy. Even VABS is not very visible on first page of Google. My suggestion:
1. Create a subdomain, e.g. https://ivabs.analyswift.com/ for the documentation
2. Add a link on analyswift front page. Currently there is a "VABS-IDE" there.

**Comment by wenbinyu-PU** [comment]
When you generate the site, is there some places to add keywords, etc?

**Comment by wenbinyu-PU** [comment]
Create a link I can understand. We can do something similar as VABS-IDE. However, I don't understand why to create a subdomain. Does it mean we need two websites? Or when anybody types ivabs.analyswift.co, it automatically goes to https://wenbinyugroup.github.io/ivabs/?

**Comment by duhd1993** [comment]
> Does it mean we need two websites?

No


> Or when anybody types ivabs.analyswift.co, it automatically goes to https://wenbinyugroup.github.io/ivabs/?

People only see https://ivabs.analyswift.com，use this as main domain. I feel it's more concise and professional.

> When you generate the site, is there some places to add keywords, etc?

I will look into this. There is a possibility to add some meta data only visible to search engine.

**Comment by wenbinyu-PU** [comment]
> > Does it mean we need two websites?
> 
> No
> 
> > Or when anybody types ivabs.analyswift.co, it automatically goes to https://wenbinyugroup.github.io/ivabs/?
> 
> People only see https://ivabs.analyswift.com ，use this as main domain. I feel it's more concise and professional.
Do you mean that github will automatically generated html files to be hosted on ivabs.analyswift.com?

**Comment by duhd1993** [comment]
Yes. I can set the domain to ivabs.analyswift.com, but the person managing the domain also need to make a small change in setting.

**Comment by wenbinyu-PU** [comment]
Let us use the current site as is now. Allan will create a separate page and link to our site. Let us keep use this site and the repo to increase its activities, I believe it will be indexed by Google soon.

**Comment by wenbinyu-PU** [comment]
A page is created for iVABS linking to the documentation site: https://analyswift.com/ivabs-framework-for-optimization-parametric-studies-uncertainty-quantifications/

**Comment by duhd1993** [comment]
I just added keywords in metadata. It's in https://github.com/wenbinyugroup/ivabs/edit/main/docs/source/index.rst
You can try to edit it. It will show in HTML source code. 

I also suggest we use a more descriptive title instead of "Welcome to iVABS Documentation"

I also subscribed analysis from Google. The data is not ready yet. we will see how google views the site later.

**Comment by duhd1993** [comment]
Added Sitemap https://wenbinyugroup.github.io/ivabs/sitemap.xml which should help SEO

**Comment by wenbinyu-PU** [comment]
Thanks a lot! I hope in the near future, people can search composite blades, or composite beams to find iVABS.

**Comment by duhd1993** [comment]
The site is now indexed by Google. I can find it on first page when searching ivabs

**Comment by wenbinyu-PU** [comment]
that is great. Thanks a lot! We should have done it earlier, then all the traffic we have will boost it up further.

**Comment by wenbinyu-PU** [comment]
Ok. I will ask Allan to put a page for iVABS.
