### ISSUE TITLE
Issue on page /ivabs/install/linux.html

### ISSUE THREAD

**Issue by wenbinyu-PU** [wenbinyugroup/ivabs#30]
One this page, in section Installer, item 4, we have the following: 
_Environment variables of PATH, LD_LIBRARY_PATH and PYTHONPATH can be updated automatically (wrote to the shell startup file such as .bash_profile). However, if your shell/terminal uses a different startup file such as .bashrc, you can set these environmental variables by yourself._

However, from what I remember, the installer can detect quite a few different startup file. If yes, please correct the description.

**Comment by duhd1993** [comment]
It can detect bash/zsh/csh/tcsh. bash/zsh are most commonly used. csh/tcsh is used by army folks. But there can be other options, then they have to do it manually. That's what I mean.

**Comment by wenbinyu-PU** [comment]
From what it describes on the page right, it only works for .bash_profile. Can you describe it more accurately?

**Comment by unitasium** [comment]
added more instructions.
