### ISSUE TITLE
windows portable

### ISSUE THREAD

**Issue by wenbinyu-PU** [wenbinyugroup/ivabs#32]
there is no env.cmd included. 
there is no dakota included.

**Comment by unitasium** [comment]
1. instructions in doc have been updated.
2. added and reuploaded.

**Comment by wenbinyu-PU** [comment]
I tried. A few issues:
1. vabslib.dll psprolib.dll belongs to vabs released are also packaged inside the bin
2. env.cmd is not used in the instruction. I suggest to delete. 
3. I tried to follow the instruction and run the example, it does not work. screenshot attached. 
![image](https://user-images.githubusercontent.com/78181625/170691765-ebd529c3-269e-47e8-a11d-d6dd7e7ced52.png)

**Comment by unitasium** [comment]
1. package updated and reuploaded.
2. it has been deleted already.
3. have you defined `IVABS_ROOT`? after setting variables, you can always use `echo %path%` to check if it is updated correctly.
