### ISSUE TITLE
Clean hidden character ^M from input files

### ISSUE THREAD

**Issue by rdrclrbh** [wenbinyugroup/ivabs#43]
This occurs due to an incompatibility between windows and unix text files. Unix does LF, while windows does LF CR, and the CR shows up as a ^M. Stripping this from the files should give a clean Unix file.

**Comment by unitasium** [comment]
@rdrclrbh Which files have this issue?

**Comment by rdrclrbh** [comment]
No specific files. A file that Mike was working with added these when he edited it, and he had to use a utility like dos2unix to clean it up.
