### ISSUE TITLE
Ignore blank lines in input files

### ISSUE THREAD

**Issue by rdrclrbh** [wenbinyugroup/ivabs#44]
Current code trips up if there are blank lines in the input files. iVABS shoudl be able to ignore / handle blank lines in an input file.

**Comment by unitasium** [comment]
@rdrclrbh Could you describe the issue more specifically?

**Comment by rdrclrbh** [comment]
Please see snippet below from a .dat file we tried to use (see blank lines in input):

---- Start of snippet------
***begin-RCAS-file: UH60_SPEC2B_PROP.TAB  ***
!M REFLENGTH
  26.8333

!M BEA
0.00000   1.0E+8
1.00000   1.0E+8

!M BEIYY   
0.04658   3.8208E+05
0.04682   3.8208E+05
0.04682   3.8208E+05
0.04713   3.8208E+05
0.04713   6.1405E+05
0.10093   6.1405E+05
0.10093   6.5067E+05
0.15528   6.5067E+05
0.15528   1.9162E+05
0.23292   1.9162E+05
0.23292   1.5417E+05
0.28509   1.5417E+05
0.28509   1.5417E+05
0.33727   1.5417E+05
0.33727   1.5417E+05
---- End of Snippet----

**Comment by unitasium** [comment]
Fixed. Updated code will be uploaded soon.
