### ISSUE TITLE
Variable names in data request consistent with RCAS prop table variable names.

### ISSUE THREAD

**Issue by rdrclrbh** [wenbinyugroup/ivabs#55]
It seems that the readRcasProp method is hard coded for what variable names it is looking for in the RCAS prop table (prop.dat). For example, I have a case wher the variable name for CG offset in the RCAS table is BCGOFF. However, if I enter bcgoff in the data request it crashes the dakota point with a write output error, presumably becuase it could not obtain any cgoff data from the RCAS prop table. The only way I can get this wo work is enter in the data request bcgoffy, and change the table entry in the prop.dat file from BCGOFF to BCGOFFY.  

iVABS needs to be more flexible on the variable names that can be specified in the data request so that a user can specify any variable that is listed in the RCAS prop.dat file as it appears in that file (not case sensitive).

**Comment by unitasium** [comment]
`readRcasProp()` is called in `data_proc_funcs.dakota_postpro()` of the custom script, correct? If yes, could you print the variable `ref_prop` returned by this function and let me know what the keys are in this dictionary?

For beam properties, this function does not have hard coded names. All names are read as is, as long as they start with the symbol `!`. As for case sensitivity, users have the full control in the custom script `data_proc_funcs`. I can also update the code to convert the property names to all lower/upper cases, but I need more information. Is this file (`prop.dat`) case sensitive? For example, will `BCGOFFY` and `BCGOFFy` be the same or different things (which could represent the same quantity in two different coordinate systems)?

**Comment by rdrclrbh** [comment]
What I mean by case insensitive is that in the .yml file one could specify the variable in one case and the case could be totally different in the RCAS file. e.g., in yaml "bcgoffy" and in the RCAS file "BCOFFY" or vice versa. Or is could be any mix of that, e.g., BCOFFy as in the example you provided. Let me see if i can look at the keys returned  in ref_prop.

**Comment by unitasium** [comment]
I know. The thing is, to achieve this feature, we need to first make sure that the `prop.dat` file itself is case insensitive, which means that there cannot be the case where both `BCGOFFY` and `BCGOFFy` exist in the same file at the same time. Otherwise, when user inputs `bcgoffy`, the code cannot match the keyword.

**Comment by rdrclrbh** [comment]
Right, the source file prop.dat is case insensitive. I get your point now.

**Comment by rdrclrbh** [comment]
what should the readRcasProp() method return? I have tried to print the keys from , but can't seem to ref_prop but I am having trouble with that. Is it supposed to return dictionary that contains of all of the properties available in the prop.dat file?

**Comment by unitasium** [comment]
Yes. It is supposed to return a dictionary:

```
prop = {
        'BGJ': {
            'x': [],
            'y': []
        },
        ...
    }
```

where `x` and `y` are the first and second column of `BGJ` in `prop.dat`, respectively.

**Comment by rdrclrbh** [comment]
OK, now that I was able to eliminate an error I am able to see the dict keys:

dict_keys(['REFLENGTH', 'BEA', 'BEIYY', 'BEIZZ', 'BGJ', 'BMPL', 'BKMYY', 'BKMZZ', 'BSTRUCTW', 'BCGOFF', 'BEIYZ', 'BKMYZ', 'BCGOFFZ', 'BTOFFY', 'BTOFFZ', 'BYMODUL', 'BSMODUL', 'BMISC'])

That is what I expect. And I think that if I enter a value from this list in the data request it does work. I am testing a case now to confirm.

**Comment by rdrclrbh** [comment]
I think that this issue is resolved.
