### ISSUE TITLE
Layup direction issue

### ISSUE THREAD

**Issue by JWS625** [wenbinyugroup/ivabs#59]
This might have to do with preVABS, but when I give different layup direction (right direction for skin and left for spar), it does not follow that and just use the default left direction. The baseline direction is counter-clockwise. In the image that shows the corner of the spar, you can see that the the all horizontal layups are below the baseline (top line) where it is supposed to have spar layup below the line and skin layup above the line by the setup (first image). 
![layup_setup](https://github.com/wenbinyugroup/ivabs/assets/95206221/51fb511a-6709-49da-a6bb-2fd3998946c1)
![spar_corner](https://github.com/wenbinyugroup/ivabs/assets/95206221/276632e3-64b3-4d15-870f-38c4be59a787)
![spar](https://github.com/wenbinyugroup/ivabs/assets/95206221/01f14c7c-8584-40c4-9493-b33ba7d2e79b)

**Comment by unitasium** [comment]
I think you may need to define the skin and the spar as two `component`s, although they are sharing some lines. Layups belonging to a `segments` can only have the same direction.

**Comment by JWS625** [comment]
OK, I just tried separate components for skin and spar. But, now it is not able to generate mesh.


![error](https://github.com/wenbinyugroup/ivabs/assets/95206221/f8553f04-1a57-47e5-b5a4-560a466fd68b)
![spar_layup_setup](https://github.com/wenbinyugroup/ivabs/assets/95206221/08ed3a2d-6a78-4135-be92-8065ebf316e8)

**Comment by JWS625** [comment]
Would there be any thoughts on this issue by any chance? 
There was not much change from the first design to the second one, so I really don't understand why iVABS is not able to generate the mesh.

**Comment by unitasium** [comment]
Could you share the input file?
